// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/jestebanrods/edu-golang/aws-testing/lambda/graphql/v1/internal"
)

// Injectors from wire.go:

func Initialize() (*internal.Handler, error) {
	graphQLSchema := SchemaFileProvider()
	personRepository := internal.NewPersonRepositoy()
	queries := internal.NewQueries(personRepository)
	schema := SchemaProvider(graphQLSchema, queries)
	handler := internal.NewHandler(schema)
	return handler, nil
}
